services:
  cache.data_collector:
    class: Cache\CacheBundle\DataCollector\CacheDataCollector
    tags:
      - { name: data_collector, template: '@Cache/Collector/cache.html.twig', id: 'php-cache' }

  cache.proxy_factory:
    class: Cache\CacheBundle\DataCollector\ProxyFactory
    arguments: ['%kernel.cache_dir%/phpcache/proxy']

  cache.decorating_factory:
    class: Cache\CacheBundle\DataCollector\DecoratingFactory
    arguments: ["@cache.proxy_factory"]
    public: false
