services:
  cache.data_collector:
    class: Cache\CacheBundle\DataCollector\CacheDataCollector
    tags:
      - { name: data_collector, template: 'CacheBundle:Collector:cache.html.twig', id: 'cache' }
